/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai6;

/**
 *
 * @author MyPC
 */
public class bai_6 extends javax.swing.JFrame {

    /**
     * Creates new form bai_6
     */
    public bai_6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroupPhepT = new javax.swing.ButtonGroup();
        jPnRoot = new javax.swing.JPanel();
        jPnTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPnBot = new javax.swing.JPanel();
        jPnMid = new javax.swing.JPanel();
        jPnTV = new javax.swing.JPanel();
        nutGiai = new javax.swing.JButton();
        nutXoa = new javax.swing.JButton();
        nutThoat = new javax.swing.JButton();
        jPnNhapS = new javax.swing.JPanel();
        jLbNhapA = new javax.swing.JLabel();
        jLbNhapB = new javax.swing.JLabel();
        hienThiA = new javax.swing.JTextField();
        hienThiB = new javax.swing.JTextField();
        jPnChonPT = new javax.swing.JPanel();
        nutCong = new javax.swing.JRadioButton();
        nutTru = new javax.swing.JRadioButton();
        nutNhan = new javax.swing.JRadioButton();
        nutChia = new javax.swing.JRadioButton();
        jLbKetQ = new javax.swing.JLabel();
        hienThiKQ = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnRoot.setBackground(new java.awt.Color(255, 255, 255));
        jPnRoot.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Cộng Trừ Nhân Chia");
        jPnTop.add(jLabel1);

        jPnRoot.add(jPnTop, java.awt.BorderLayout.PAGE_START);

        jPnBot.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPnBotLayout = new javax.swing.GroupLayout(jPnBot);
        jPnBot.setLayout(jPnBotLayout);
        jPnBotLayout.setHorizontalGroup(
            jPnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPnBotLayout.setVerticalGroup(
            jPnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jPnRoot.add(jPnBot, java.awt.BorderLayout.PAGE_END);

        jPnTV.setBackground(new java.awt.Color(255, 153, 153));
        jPnTV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn tác vụ", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        nutGiai.setBackground(new java.awt.Color(102, 255, 255));
        nutGiai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutGiai.setText(" Giải   ");

        nutXoa.setBackground(new java.awt.Color(102, 255, 255));
        nutXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutXoa.setText("Xoá");

        nutThoat.setBackground(new java.awt.Color(102, 255, 255));
        nutThoat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutThoat.setText("Thoát");

        javax.swing.GroupLayout jPnTVLayout = new javax.swing.GroupLayout(jPnTV);
        jPnTV.setLayout(jPnTVLayout);
        jPnTVLayout.setHorizontalGroup(
            jPnTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nutGiai, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
            .addComponent(nutXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nutThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPnTVLayout.setVerticalGroup(
            jPnTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTVLayout.createSequentialGroup()
                .addComponent(nutGiai)
                .addGap(18, 18, 18)
                .addComponent(nutXoa)
                .addGap(18, 18, 18)
                .addComponent(nutThoat)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPnNhapS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "nhập 2 số a và b", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLbNhapA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLbNhapA.setText("nhập a: ");

        jLbNhapB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLbNhapB.setText("nhập b: ");

        jPnChonPT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn phép toán:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPnChonPT.setLayout(new java.awt.GridLayout(2, 2));

        btGroupPhepT.add(nutCong);
        nutCong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutCong.setText("Cộng");
        jPnChonPT.add(nutCong);

        btGroupPhepT.add(nutTru);
        nutTru.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutTru.setText("Trừ");
        jPnChonPT.add(nutTru);

        btGroupPhepT.add(nutNhan);
        nutNhan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutNhan.setText("Nhân");
        jPnChonPT.add(nutNhan);

        btGroupPhepT.add(nutChia);
        nutChia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutChia.setText("Chia");
        jPnChonPT.add(nutChia);

        jLbKetQ.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLbKetQ.setText("Kết quả:");

        javax.swing.GroupLayout jPnNhapSLayout = new javax.swing.GroupLayout(jPnNhapS);
        jPnNhapS.setLayout(jPnNhapSLayout);
        jPnNhapSLayout.setHorizontalGroup(
            jPnNhapSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnNhapSLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPnNhapSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPnNhapSLayout.createSequentialGroup()
                        .addComponent(jLbKetQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hienThiKQ))
                    .addGroup(jPnNhapSLayout.createSequentialGroup()
                        .addGroup(jPnNhapSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLbNhapA, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(jLbNhapB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnNhapSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnNhapSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hienThiA, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(hienThiB))
                            .addComponent(jPnChonPT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPnNhapSLayout.setVerticalGroup(
            jPnNhapSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnNhapSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnNhapSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbNhapA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hienThiA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnNhapSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbNhapB)
                    .addComponent(hienThiB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPnChonPT, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPnNhapSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbKetQ)
                    .addComponent(hienThiKQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPnMidLayout = new javax.swing.GroupLayout(jPnMid);
        jPnMid.setLayout(jPnMidLayout);
        jPnMidLayout.setHorizontalGroup(
            jPnMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnMidLayout.createSequentialGroup()
                .addComponent(jPnTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnNhapS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPnMidLayout.setVerticalGroup(
            jPnMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnTV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPnMidLayout.createSequentialGroup()
                .addComponent(jPnNhapS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPnRoot.add(jPnMid, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btGroupPhepT;
    private javax.swing.JTextField hienThiA;
    private javax.swing.JTextField hienThiB;
    private javax.swing.JTextField hienThiKQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbKetQ;
    private javax.swing.JLabel jLbNhapA;
    private javax.swing.JLabel jLbNhapB;
    private javax.swing.JPanel jPnBot;
    private javax.swing.JPanel jPnChonPT;
    private javax.swing.JPanel jPnMid;
    private javax.swing.JPanel jPnNhapS;
    private javax.swing.JPanel jPnRoot;
    private javax.swing.JPanel jPnTV;
    private javax.swing.JPanel jPnTop;
    private javax.swing.JRadioButton nutChia;
    private javax.swing.JRadioButton nutCong;
    private javax.swing.JButton nutGiai;
    private javax.swing.JRadioButton nutNhan;
    private javax.swing.JButton nutThoat;
    private javax.swing.JRadioButton nutTru;
    private javax.swing.JButton nutXoa;
    // End of variables declaration//GEN-END:variables
}
