/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab2;

/**
 *
 * @author MyPC
 */
public class Lab_2 extends javax.swing.JFrame {

    /**
     * Creates new form Lab_2
     */
    public Lab_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnRoot = new javax.swing.JPanel();
        jPnTop = new javax.swing.JPanel();
        jTFhienThi = new javax.swing.JTextField();
        jPnBot = new javax.swing.JPanel();
        so1 = new javax.swing.JButton();
        so2 = new javax.swing.JButton();
        so3 = new javax.swing.JButton();
        chia = new javax.swing.JButton();
        canB2 = new javax.swing.JButton();
        so4 = new javax.swing.JButton();
        so5 = new javax.swing.JButton();
        so6 = new javax.swing.JButton();
        nhan = new javax.swing.JButton();
        phanTram = new javax.swing.JButton();
        so7 = new javax.swing.JButton();
        so8 = new javax.swing.JButton();
        so9 = new javax.swing.JButton();
        tru = new javax.swing.JButton();
        ham = new javax.swing.JButton();
        so0 = new javax.swing.JButton();
        soAmD = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        cong = new javax.swing.JButton();
        bang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnRoot.setLayout(new java.awt.BorderLayout());

        jPnTop.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTFhienThi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTFhienThi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFhienThi.setText("0");

        javax.swing.GroupLayout jPnTopLayout = new javax.swing.GroupLayout(jPnTop);
        jPnTop.setLayout(jPnTopLayout);
        jPnTopLayout.setHorizontalGroup(
            jPnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnTopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTFhienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPnTopLayout.setVerticalGroup(
            jPnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTFhienThi, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jPnRoot.add(jPnTop, java.awt.BorderLayout.PAGE_START);

        jPnBot.setLayout(new java.awt.GridLayout(4, 5));

        so1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so1.setText("1");
        so1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so1ActionPerformed(evt);
            }
        });
        jPnBot.add(so1);

        so2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so2.setText("2");
        so2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so2ActionPerformed(evt);
            }
        });
        jPnBot.add(so2);

        so3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so3.setText("3");
        so3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so3ActionPerformed(evt);
            }
        });
        jPnBot.add(so3);

        chia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        chia.setText("/");
        chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiaActionPerformed(evt);
            }
        });
        jPnBot.add(chia);

        canB2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        canB2.setText("sqrt");
        jPnBot.add(canB2);

        so4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so4.setText("4");
        so4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so4ActionPerformed(evt);
            }
        });
        jPnBot.add(so4);

        so5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so5.setText("5");
        so5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so5ActionPerformed(evt);
            }
        });
        jPnBot.add(so5);

        so6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so6.setText("6");
        so6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so6ActionPerformed(evt);
            }
        });
        jPnBot.add(so6);

        nhan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nhan.setText("*");
        nhan.setToolTipText("");
        nhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanActionPerformed(evt);
            }
        });
        jPnBot.add(nhan);

        phanTram.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        phanTram.setText("%");
        jPnBot.add(phanTram);

        so7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so7.setText("7");
        so7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so7ActionPerformed(evt);
            }
        });
        jPnBot.add(so7);

        so8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so8.setText("8");
        so8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so8ActionPerformed(evt);
            }
        });
        jPnBot.add(so8);

        so9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so9.setText("9");
        so9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so9ActionPerformed(evt);
            }
        });
        jPnBot.add(so9);

        tru.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tru.setText("-");
        tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truActionPerformed(evt);
            }
        });
        jPnBot.add(tru);

        ham.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ham.setText("1/x");
        jPnBot.add(ham);

        so0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        so0.setText("0");
        so0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so0ActionPerformed(evt);
            }
        });
        jPnBot.add(so0);

        soAmD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        soAmD.setText("+/-");
        jPnBot.add(soAmD);

        xoa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        xoa.setText("C");
        jPnBot.add(xoa);

        cong.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cong.setText("+");
        cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congActionPerformed(evt);
            }
        });
        jPnBot.add(cong);

        bang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bang.setText("=");
        bang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangActionPerformed(evt);
            }
        });
        jPnBot.add(bang);

        jPnRoot.add(jPnBot, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void so1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so1ActionPerformed
        // TODO add your handling code here:
        String gt=this.jTFhienThi.getText();
        if (gt.length()<12){
            if(gt.equals("0")) gt="";
            long so = Long.parseLong(gt+ so1.getText());
            this.jTFhienThi.setText(String.valueOf(so));
        }
        
         
        
    }//GEN-LAST:event_so1ActionPerformed

    private void so2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so2ActionPerformed
        // TODO add your handling code here:
        String gt=this.jTFhienThi.getText();
        if (gt.length()<12){
            if(gt.equals("0")) gt="";
            long so=Long.parseLong(gt+so2.getText());
            this.jTFhienThi.setText(String.valueOf(so));
            
        }
    }//GEN-LAST:event_so2ActionPerformed

    private void so3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so3ActionPerformed
        // TODO add your handling code here:
        String gt=this.jTFhienThi.getText();
        if (gt.length()<12){
            if(gt.equals("0")) gt="";
            long so=Long.parseLong(gt+so3.getText());
            this.jTFhienThi.setText(String.valueOf(so));
            
        }
    }//GEN-LAST:event_so3ActionPerformed

    private void so4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so4ActionPerformed
        // TODO add your handling code here:
        String gt=this.jTFhienThi.getText();
        if (gt.length()<12) {
            if(gt.equals("0")) gt="";
            long so=Long.parseLong(gt+so4.getText());
            this.jTFhienThi.setText(String.valueOf(so));
           
            
        }
    }//GEN-LAST:event_so4ActionPerformed

    private void so5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so5ActionPerformed
        // TODO add your handling code here:
        String gt=this.jTFhienThi.getText();
        if (gt.length()<12) {
            if(gt.equals("o")) gt="";
            long so=Long.parseLong(gt+so5.getText());
            this.jTFhienThi.setText(String.valueOf(so));
            
        }
    }//GEN-LAST:event_so5ActionPerformed

    private void so6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so6ActionPerformed
        // TODO add your handling code here:
        String gt=this.jTFhienThi.getText();
        if (gt.length()<12) {
            if(gt.equals("0")) gt="";
            long so=Long.parseLong(gt+so6.getText());
            this.jTFhienThi.setText(String.valueOf(so));
            
        }
    }//GEN-LAST:event_so6ActionPerformed

    private void so7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so7ActionPerformed
        // TODO add your handling code here
        String gt=this.jTFhienThi.getText();
        if (gt.length()<12) {
            if(gt.equals("0")) gt="";
            long so=Long.parseLong(gt+so7.getText());
            this.jTFhienThi.setText(String.valueOf(so));
            
        }
    }//GEN-LAST:event_so7ActionPerformed

    private void so8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so8ActionPerformed
        // TODO add your handling code here:
        String gt=this.jTFhienThi.getText();
        if (gt.length()<12) {
            if(gt.equals("0")) gt="";
            long so=Long.parseLong(gt+so8.getText());
            this.jTFhienThi.setText(String.valueOf(so));
            
        }
    }//GEN-LAST:event_so8ActionPerformed

    private void so9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so9ActionPerformed
        // TODO add your handling code here:
        String gt=this.jTFhienThi.getText();
        if (gt.length()<12) {
            if(gt.equals("0")) gt="";
            long so=Long.parseLong(gt+so9.getText());
            this.jTFhienThi.setText(String.valueOf(so));
            
        }
    }//GEN-LAST:event_so9ActionPerformed

    private void so0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so0ActionPerformed
        // TODO add your handling code here:
        String gt =this.jTFhienThi.getText();
        if (gt.length()<12) {
            if(gt.equals("0")) gt="";
            long so=Long.parseLong(gt+so0.getText());
            this.jTFhienThi.setText(String.valueOf(so));
            
        }
    }//GEN-LAST:event_so0ActionPerformed

    private void chiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiaActionPerformed
        // TODO add your handling code here:
        this.a=Long.parseLong(this.jTFhienThi.getText());
        if (this.a !=0) {
            this.pheptoan = "/";
            this.jTFhienThi.setText("o");
            
        }
    }//GEN-LAST:event_chiaActionPerformed

    private void nhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanActionPerformed
        // TODO add your handling code here:
        this.a =Long.parseLong(this.jTFhienThi.getText());
        this.pheptoan = "*";
        this.jTFhienThi.setText("0");
    }//GEN-LAST:event_nhanActionPerformed

    private void truActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truActionPerformed
        // TODO add your handling code here:
        this.a =Long.parseLong(this.jTFhienThi.getText());
        this.pheptoan = "-";
        this.jTFhienThi.setText("0");
    }//GEN-LAST:event_truActionPerformed

    private void congActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congActionPerformed
        // TODO add your handling code here:
        this.a = Long.parseLong(this.jTFhienThi.getText());
        this.pheptoan = "+";
        this.jTFhienThi.setText("0");
    }//GEN-LAST:event_congActionPerformed

    private void bangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangActionPerformed
        // TODO add your handling code here:
        if (this.pheptoan.length()>0) {
            long b=Long.parseLong(this.jTFhienThi.getText());
            if (this.pheptoan.equals("+")) {
                long kq = this.a + b;
                this.jTFhienThi.setText(String.valueOf(kq));
            }else if (this.pheptoan.equals("-")) {
                long kq = this.a - b;
                this.jTFhienThi.setText(String.valueOf(kq));
            }else if (this.pheptoan.equals("*")) {
                long kq = this.a * b;
                this.jTFhienThi.setText(String.valueOf(kq));
            }else if (this.pheptoan.equals("/")) {
                float kq = (float)this.a / b;
                this.jTFhienThi.setText(String.valueOf(kq));
            }
            this.pheptoan = "";
            this.a=0;
        }
    }//GEN-LAST:event_bangActionPerformed
    private long a=0;
    private String pheptoan="";
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab_2().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bang;
    private javax.swing.JButton canB2;
    private javax.swing.JButton chia;
    private javax.swing.JButton cong;
    private javax.swing.JButton ham;
    private javax.swing.JPanel jPnBot;
    private javax.swing.JPanel jPnRoot;
    private javax.swing.JPanel jPnTop;
    private javax.swing.JTextField jTFhienThi;
    private javax.swing.JButton nhan;
    private javax.swing.JButton phanTram;
    private javax.swing.JButton so0;
    private javax.swing.JButton so1;
    private javax.swing.JButton so2;
    private javax.swing.JButton so3;
    private javax.swing.JButton so4;
    private javax.swing.JButton so5;
    private javax.swing.JButton so6;
    private javax.swing.JButton so7;
    private javax.swing.JButton so8;
    private javax.swing.JButton so9;
    private javax.swing.JButton soAmD;
    private javax.swing.JButton tru;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
