/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai7;

/**
 *
 * @author MyPC
 */
public class bai_7 extends javax.swing.JFrame {

    /**
     * Creates new form bai_7
     */
    public bai_7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnRoot = new javax.swing.JPanel();
        jPntop = new javax.swing.JPanel();
        tieuDe = new javax.swing.JLabel();
        jPnBot = new javax.swing.JPanel();
        nutDongCT = new javax.swing.JButton();
        jPnMid = new javax.swing.JPanel();
        jPnChonTacVu = new javax.swing.JPanel();
        nutTDenSChan = new javax.swing.JButton();
        nutTDenSLe = new javax.swing.JButton();
        nutTDenSNTo = new javax.swing.JButton();
        nutBoTDen = new javax.swing.JButton();
        nutXoaCGTDTDen = new javax.swing.JButton();
        nutTGTTrongJL = new javax.swing.JButton();
        jPnNhapTTin = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        nutNhap = new javax.swing.JButton();
        hienThiSo = new javax.swing.JTextField();
        jCBChonSoAm = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnRoot.setLayout(new java.awt.BorderLayout());

        tieuDe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tieuDe.setForeground(new java.awt.Color(0, 0, 204));
        tieuDe.setText("Thao tác trên JList - Checkbox");
        jPntop.add(tieuDe);

        jPnRoot.add(jPntop, java.awt.BorderLayout.PAGE_START);

        jPnBot.setBackground(new java.awt.Color(255, 153, 204));

        nutDongCT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutDongCT.setText("Đóng chương trình");
        jPnBot.add(nutDongCT);

        jPnRoot.add(jPnBot, java.awt.BorderLayout.PAGE_END);

        jPnChonTacVu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn tác vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        nutTDenSChan.setBackground(new java.awt.Color(153, 204, 255));
        nutTDenSChan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutTDenSChan.setText("Tô đen số chẵn");

        nutTDenSLe.setBackground(new java.awt.Color(153, 204, 255));
        nutTDenSLe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutTDenSLe.setText("Tô đen số lẻ");

        nutTDenSNTo.setBackground(new java.awt.Color(153, 204, 255));
        nutTDenSNTo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutTDenSNTo.setText("Tô đen số nguyên tố");

        nutBoTDen.setBackground(new java.awt.Color(153, 204, 255));
        nutBoTDen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutBoTDen.setText("Bỏ tô đen");
        nutBoTDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutBoTDenActionPerformed(evt);
            }
        });

        nutXoaCGTDTDen.setBackground(new java.awt.Color(153, 204, 255));
        nutXoaCGTDTDen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutXoaCGTDTDen.setText("Xoá các giá trị đang tô đen");

        nutTGTTrongJL.setBackground(new java.awt.Color(153, 204, 255));
        nutTGTTrongJL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutTGTTrongJL.setText("Tổng giá trị trong JList");

        javax.swing.GroupLayout jPnChonTacVuLayout = new javax.swing.GroupLayout(jPnChonTacVu);
        jPnChonTacVu.setLayout(jPnChonTacVuLayout);
        jPnChonTacVuLayout.setHorizontalGroup(
            jPnChonTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnChonTacVuLayout.createSequentialGroup()
                .addGroup(jPnChonTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nutTDenSChan)
                    .addComponent(nutTDenSLe)
                    .addComponent(nutTDenSNTo)
                    .addComponent(nutBoTDen)
                    .addComponent(nutXoaCGTDTDen)
                    .addComponent(nutTGTTrongJL))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPnChonTacVuLayout.setVerticalGroup(
            jPnChonTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnChonTacVuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nutTDenSChan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nutTDenSLe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nutTDenSNTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nutBoTDen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nutXoaCGTDTDen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nutTGTTrongJL)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPnNhapTTin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "4", "5", "6", "9", "11", "17", "18", "35", "67", "77", "84", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        nutNhap.setBackground(new java.awt.Color(153, 204, 255));
        nutNhap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nutNhap.setText("Nhập");
        nutNhap.setBorder(null);

        jCBChonSoAm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCBChonSoAm.setText("Chọn nhập số âm");

        javax.swing.GroupLayout jPnNhapTTinLayout = new javax.swing.GroupLayout(jPnNhapTTin);
        jPnNhapTTin.setLayout(jPnNhapTTinLayout);
        jPnNhapTTinLayout.setHorizontalGroup(
            jPnNhapTTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnNhapTTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nutNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hienThiSo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBChonSoAm)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPnNhapTTinLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPnNhapTTinLayout.setVerticalGroup(
            jPnNhapTTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnNhapTTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnNhapTTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nutNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hienThiSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBChonSoAm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPnMidLayout = new javax.swing.GroupLayout(jPnMid);
        jPnMid.setLayout(jPnMidLayout);
        jPnMidLayout.setHorizontalGroup(
            jPnMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnMidLayout.createSequentialGroup()
                .addComponent(jPnChonTacVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPnNhapTTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPnMidLayout.setVerticalGroup(
            jPnMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnMidLayout.createSequentialGroup()
                .addComponent(jPnChonTacVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPnMidLayout.createSequentialGroup()
                .addComponent(jPnNhapTTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPnRoot.add(jPnMid, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nutBoTDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutBoTDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nutBoTDenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai_7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hienThiSo;
    private javax.swing.JCheckBox jCBChonSoAm;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPnBot;
    private javax.swing.JPanel jPnChonTacVu;
    private javax.swing.JPanel jPnMid;
    private javax.swing.JPanel jPnNhapTTin;
    private javax.swing.JPanel jPnRoot;
    private javax.swing.JPanel jPntop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nutBoTDen;
    private javax.swing.JButton nutDongCT;
    private javax.swing.JButton nutNhap;
    private javax.swing.JButton nutTDenSChan;
    private javax.swing.JButton nutTDenSLe;
    private javax.swing.JButton nutTDenSNTo;
    private javax.swing.JButton nutTGTTrongJL;
    private javax.swing.JButton nutXoaCGTDTDen;
    private javax.swing.JLabel tieuDe;
    // End of variables declaration//GEN-END:variables
}
