/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab3;

import javax.swing.JOptionPane;

/**
 *
 * @author MyPC
 */
public class Lab_3 extends javax.swing.JFrame {

    /**
     * Creates new form Lab_3
     */
    public Lab_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnRoot = new javax.swing.JPanel();
        jPnTop = new javax.swing.JPanel();
        jLbTD = new javax.swing.JLabel();
        jPnBot = new javax.swing.JPanel();
        batDau = new javax.swing.JButton();
        jPnMid = new javax.swing.JPanel();
        so15 = new javax.swing.JButton();
        so14 = new javax.swing.JButton();
        so13 = new javax.swing.JButton();
        so12 = new javax.swing.JButton();
        so11 = new javax.swing.JButton();
        so10 = new javax.swing.JButton();
        so9 = new javax.swing.JButton();
        so8 = new javax.swing.JButton();
        so7 = new javax.swing.JButton();
        so6 = new javax.swing.JButton();
        so5 = new javax.swing.JButton();
        so4 = new javax.swing.JButton();
        so3 = new javax.swing.JButton();
        so2 = new javax.swing.JButton();
        so1 = new javax.swing.JButton();
        nutTrong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnRoot.setForeground(new java.awt.Color(204, 204, 255));
        jPnRoot.setLayout(new java.awt.BorderLayout());

        jLbTD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLbTD.setText("TRÒ CHƠI XẾP Ô SỐ");
        jPnTop.add(jLbTD);

        jPnRoot.add(jPnTop, java.awt.BorderLayout.PAGE_START);

        jPnBot.setForeground(new java.awt.Color(153, 255, 255));

        batDau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        batDau.setText("Bắt Đầu");
        batDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batDauActionPerformed(evt);
            }
        });
        jPnBot.add(batDau);

        jPnRoot.add(jPnBot, java.awt.BorderLayout.PAGE_END);

        jPnMid.setForeground(new java.awt.Color(153, 204, 255));
        jPnMid.setLayout(new java.awt.GridLayout(4, 4));

        so15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so15.setText("15");
        so15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(so15);

        so14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so14.setText("14");
        so14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(so14);

        so13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so13.setText("13");
        so13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(so13);

        so12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so12.setText("12");
        so12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(so12);

        so11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so11.setText("11");
        so11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(so11);

        so10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so10.setText("10");
        so10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(so10);

        so9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so9.setText("9");
        so9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(so9);

        so8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so8.setText("8");
        so8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(so8);

        so7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so7.setText("7");
        so7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(so7);

        so6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so6.setText("6");
        so6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(so6);

        so5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so5.setText("5");
        so5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(so5);

        so4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so4.setText("4");
        so4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(so4);

        so3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so3.setText("3");
        so3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        so3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPnMid.add(so3);

        so2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so2.setText("2");
        so2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(so2);

        so1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        so1.setText("1");
        so1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(so1);

        nutTrong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nutTrong.setText(" ");
        nutTrong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnMid.add(nutTrong);

        jPnRoot.add(jPnMid, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batDauActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog("Họ và tên từ người chơi");
        this.setTitle("Họ và Tên");
    }//GEN-LAST:event_batDauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batDau;
    private javax.swing.JLabel jLbTD;
    private javax.swing.JPanel jPnBot;
    private javax.swing.JPanel jPnMid;
    private javax.swing.JPanel jPnRoot;
    private javax.swing.JPanel jPnTop;
    private javax.swing.JButton nutTrong;
    private javax.swing.JButton so1;
    private javax.swing.JButton so10;
    private javax.swing.JButton so11;
    private javax.swing.JButton so12;
    private javax.swing.JButton so13;
    private javax.swing.JButton so14;
    private javax.swing.JButton so15;
    private javax.swing.JButton so2;
    private javax.swing.JButton so3;
    private javax.swing.JButton so4;
    private javax.swing.JButton so5;
    private javax.swing.JButton so6;
    private javax.swing.JButton so7;
    private javax.swing.JButton so8;
    private javax.swing.JButton so9;
    // End of variables declaration//GEN-END:variables
}
